routes/web.php
    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');
    Route::post('products-delete','ProductsController@delete');
    Route::post('product-more-categories-set','ProductsController@moreCategoriesSet');
    Route::post('product-picture-upload','ProductsController@pictureUpload');
    Route::put('product-gallery-upload/{id}','ProductsController@galleryUpload');
    Route::post('product-gallery/{id}/delete/{row}','ProductsController@galleryDelete');
    Route::post('product-img360/delete','ProductsController@img360Delete');

    Route::put('product-gallery-upload/{id}/360','ProductsController@galleryUpload360');

    Route::post('product-documents-upload/{id}','ProductsController@documentUpload');
    Route::post('product-documents-delete','ProductsController@documentDelete');

    Route::post('product-video/{id}/add','ProductsController@videoAdd');
    Route::post('product-video/{id}/delete','ProductsController@videoDelete');
    Route::get('products/sync','ProductsController@syncWithBilling')->name('products.sync');
    Route::resource('products', 'ProductsController');
    Route::post('products/getByCatId','ProductsController@getByCatId');
    Route::post('products/get-buy-with','ProductsController@getBuyWith');
    Route::post('products/add-to-buy-with','ProductsController@addToBuyWith');
    Route::post('products/del-from-buy-with','ProductsController@delFromBuyWith');

    Route::get('products-comments','ProductsCommentsController@index')->name('products.comments');
    Route::get('products-comments/{id}/edit','ProductsCommentsController@edit')->name('products.comments.edit');
    Route::post('products-comments/{id}/edit','ProductsCommentsController@save');
    Route::get('products-comments/{id}/delete','ProductsCommentsController@delete');

    Route::post('products-comments/emails/add','ProductsCommentsController@emailAdd');
    Route::get('products-comments/emails/{id}/delete','ProductsCommentsController@emailDelete')->name('products.comments.email-delete');


    Route::resource('services', 'ServicesController');
    Route::post('services/get-prods','ServicesController@getProds');
    Route::post('services/add-prod','ServicesController@addProd');
    Route::post('services/remove-prod','ServicesController@removeProd');
    Route::post('services/products-save-sort','ServicesController@productsSaveSort');
    Route::get('services-test/{code}','ServicesController@testService')->name('services.test');

    Route::get('news/{id}/history','NewsController@history')->name('news.history');
    Route::post('news/slug','NewsController@slug');
    Route::resource('news', 'NewsController');

    Route::get('actions/{id}/history','ActionsController@history')->name('actions.history');
    Route::post('actions/slug','ActionsController@slug');
    Route::resource('actions', 'ActionsController');

    Route::get('payments/{id}/history','PaymentsController@history')->name('payments.history');
    Route::resource('payments', 'PaymentsController');

    Route::get('tags/{id}/history','TagsController@history')->name('tags.history');
    Route::resource('tags', 'TagsController');

    Route::get('pages/{id}/history','PagesController@history')->name('pages.history');
    Route::get('pages/clear-deleted','PagesController@clearDeleted')->name('pages.clearDeleted');
    Route::resource('pages', 'PagesController');

    Route::get('sliders/{id}/history','SlidersController@history')->name('sliders.history');
    Route::resource('sliders', 'SlidersController');

    Route::get('maps','MapsController@index')->name('maps.index');
    Route::get('maps/sync','MapsController@sync')->name('maps.sync');
    Route::get('maps/add','MapsController@create')->name('maps.add');
    Route::post('maps/get-by-id','MapsController@getMarkerById');

    Route::get('menu','MenuController@index')->name('menu');
    Route::get('menu/create','MenuController@create')->name('create');
    Route::get('menu/{id}/edit','MenuController@edit')->name('menu-edit');
    Route::get('menu/show','MenuController@show')->name('menu-show');
    Route::get('menu/{id}/generate','MenuController@generate')->name('menu-generate');
    Route::post('menu/{id}/add-item','MenuController@addItem');
    Route::post('menu/{id}/items-save-sort','MenuController@itemsSaveSort');
    Route::post('menu/{id}/del-item','MenuController@delItem');
    Route::post('menu/{id}/get-item','MenuController@getItem');

    Route::post('property-value-save','PropertiesController@propertyValueSave');
    Route::post('properties-add-value','PropertiesController@propertyAddValue');
    Route::post('properties-delete','PropertiesController@delete');
    Route::post('properties-delete-value','PropertiesController@propertyDelValue');
    Route::resource('properties', 'PropertiesController');

    Route::post('categories-update-active','CategoryController@updateActive');
    Route::post('categories-save-sort','CategoryController@saveSort');
    Route::post('categories-delete','CategoryController@delete');
    Route::delete('categories/destroy', 'CategoryController@destroy')->name('categories.destroy');
    Route::resource('categories', 'CategoryController');
    Route::post('categories-add-prop','CategoryController@addProperty');
    Route::post('categories-del-prop','CategoryController@removeProperty');

    Route::post('payment-methods-delete','PaymentMethodsController@delete');
    Route::resource('payment-methods', 'PaymentMethodsController');

    Route::post('shipment-methods-delete','ShipmentMethodsController@delete');
    Route::resource('shipment-methods', 'ShipmentMethodsController');

    Route::get('orders','OrdersController@index')->name('orders');
    Route::get('orders/{id}','OrdersController@detail')->name('orders-detail');
    Route::get('orders/{id}/edit','OrdersController@edit')->name('orders-edit');
    Route::post('orders/{id}/save-status','OrdersController@statusSave');
    Route::post('orders/{id}/save','OrdersController@orderSave');
    Route::get('orders/{id}/print','OrdersController@printOrder')->name('orders-print');

    Route::get('order-status','OrdersController@statuses')->name('order-status');
    Route::post('order-status/save','OrdersController@statusesSave');
    Route::post('order-add-product','OrdersController@addProductToOrder');
    Route::post('order-delete-product','OrdersController@deleteProductInOrder');
    Route::post('order-update-product','OrdersController@updateProductInOrder');

    Route::get('faqs','FaqsController@index')->name('faqs.index');
    Route::get('faqs/create','FaqsController@groupCreate')->name('faqs.group.create');
    Route::post('faqs/store','FaqsController@groupStore');
    Route::get('faqs/{id}/edit','FaqsController@groupEdit')->name('faqs.group.edit');
    Route::put('faqs/{id}/update','FaqsController@groupUpdate');
    Route::delete('faqs/{id}','FaqsController@groupDelete');
    Route::get('faqs/{id}/elements','FaqsController@groupElements')->name('faqs.elements');
    Route::get('faqs/{id}/elements/create','FaqsController@elementCreate')->name('faqs.elements.create');
    Route::post('faqs/{id}/elements/store','FaqsController@elementStore');
    Route::get('faqs/{id}/elements/{element_id}/edit','FaqsController@elementEdit')->name('faqs.elements.edit');
    Route::put('faqs/{id}/elements/{element_id}/update','FaqsController@elementUpdate');
    Route::delete('faqs/{id}/elements/{element_id}','FaqsController@elementDelete');

    Route::get('faqs-test','FaqsController@test');

    Route::get('recommend-products','RecommendProductsController@index')->name('recommend-products');
    Route::post('recommend-products','RecommendProductsController@update');

    Route::resource('documents', 'DocumentsController');
    Route::resource('prices', 'PricesController');
    Route::resource('rules', 'RulesController');
    Route::resource('docactions', 'DocsActionsController');
    Route::resource('sertificats', 'SertificatsController');
    Route::resource('qualities', 'QualitiesController');

    Route::get('help','HelpController@index')->name('help.index');
    Route::get('help/{id}/children','HelpController@index')->name('help.children');
    Route::get('help/create','HelpController@directoryCreate')->name('help.directory.create');
    Route::post('help/store','HelpController@directoryStore')->name('help.directory.store');
    Route::get('help/{id}/edit','HelpController@directoryEdit')->name('help.directory.edit');
    Route::put('help/{id}/update','HelpController@directoryUpdate')->name('help.directory.update');
    Route::delete('help/{id}','HelpController@directoryDestroy')->name('help.directory.destroy');

    Route::get('blogs/comments','BlogCommentsController@index')->name('blog.comments.index');
    Route::get('blogs/comments/{id}','BlogCommentsController@edit')->name('blog.comments.edit');
    Route::post('blogs/comments/{id}','BlogCommentsController@update');
    Route::post('blogs/comments/{id}/moderate','BlogCommentsController@moderate');
    Route::delete('blogs/comments/{id}','BlogCommentsController@destroy')->name('blog.comments.destroy');

    Route::post('blogs/slug','BlogsController@slug');
    Route::resource('blogs', 'BlogsController');

    Route::post('blogcategories/slug','BlogCategoriesController@slug');
    Route::resource('blogcategories', 'BlogCategoriesController');

    /*
    Route::get('help/{id}/articles','HelpController@articles')->name('help.articles');
    Route::get('help/{id}/articles/create','HelpController@articleCreate')->name('help.articles.create');
    Route::post('help/{id}/articles/store','HelpController@articleStore')->name('help.articles.store');
    Route::get('help/{id}/articles/{article_id}/edit','HelpController@articleEdit')->name('help.articles.edit');
    Route::put('help/{id}/articles/{article_id}/update','HelpController@articleUpdate')->name('help.articles.update');

resources/views/admin/docactions/create.blade.php
@extends('layouts.admin')
@section('title')
    Создание акции
@endsection
@section('styles')
    <style>
        .alert-danger{
            display: none;
            position: fixed;
            width: 400px;
            top: 40%;
            left: 50%;
            margin-left: -200px;
        }
    </style>
@endsection

@section('content')

<div class="card">
    <div class="card-header">
        Создание акции
    </div>

    <div class="card-body">
        <form action="{{ route("admin.docactions.store") }}" method="POST" enctype="multipart/form-data">
            @csrf


                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group {{ $errors->has('title_ru') ? 'has-error' : '' }}">
                                <label for="title_ru">Заголовок RU*</label>
                                <input type="text" id="title_ru" name="title_ru" class="form-control title_for_slug" required value="{{ old('title_ru') }}">
                                @if($errors->has('title_ru'))
                                    <em class="invalid-feedback">
                                        {{ $errors->first('title_ru') }}
                                    </em>
                                @endif
                            </div>
                            <div class="form-group {{ $errors->has('title_ua') ? 'has-error' : '' }}">
                                <label for="title_ru">Заголовок UA*</label>
                                <input type="text" id="title_ua" name="title_ua" class="form-control" required value="{{ old('title_ua') }}">
                                @if($errors->has('title_ru'))
                                    <em class="invalid-feedback">
                                        {{ $errors->first('title_ua') }}
                                    </em>
                                @endif
                            </div>
                            <div class="form-group {{ $errors->has('title_en') ? 'has-error' : '' }}">
                                <label for="title_ru">Заголовок EN*</label>
                                <input type="text" id="title_en" name="title_en" class="form-control" required value="{{ old('title_en') }}">
                                @if($errors->has('title_en'))
                                    <em class="invalid-feedback">
                                        {{ $errors->first('title_en') }}
                                    </em>
                                @endif
                            </div>

                        </div>
                        <div class="col-md-4">

                            <div class="form-group">
                                <div class="toggle-label">Активность</div>
                                <div class="toggle-btn">
                                    <input type="checkbox" class="cb-value" name="active" value="1" />
                                    <span class="round-btn"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="slug">Сортировка</label>
                                <input type="number" id="sort" name="sort" class="form-control" min="1" max="999999" value="{{ old('sort') }}">
                            </div>

                            <div class="form-group {{ $errors->has('file') ? 'has-error' : '' }}">
                                <label for="image">Документ</label><br />
                                <label class="label" data-toggle="tooltip" title="Загрузить документ">
                                    <input type="file" class="" name="file">
                                </label>
                                @if($errors->has('file'))
                                    <em class="invalid-feedback">
                                        {{ $errors->first('file') }}
                                    </em>
                                @endif
                            </div>

                        </div>
                    </div>





            <div>
                <button class="btn btn-success" type="submit"><i class="fas fa-check"></i> Сохранить</button>
                <a href="/admin/docactions" class="btn btn-secondary"><i class="fas fa-remove"></i> Отменить</a>
            </div>

        </form>
    </div>
</div>

@endsection

@section('scripts')
@endsection

resources/views/admin/docactions/edit.blade.php
@extends('layouts.admin')
@section('title')
    Редактирование акции
@endsection
@section('styles')
    <style>
        .alert-danger{
            display: none;
            position: fixed;
            width: 400px;
            top: 40%;
            left: 50%;
            margin-left: -200px;
        }
    </style>
@endsection

@section('content')

    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-secondary" href="{{ route("admin.docactions.index") }}">
                <i class="fas fa-chevron-left"></i> Назад
            </a>
        </div>
    </div>

<div class="card">

    <div class="card-header">
        Редактирование акции
    </div>

    <div class="card-body">
        <form action="{{ route("admin.docactions.update", [$docAction->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')


            <div class="tab-content" id="myTabContent">

                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group {{ $errors->has('title_ru') ? 'has-error' : '' }}">
                                <label for="title_ru">Заголовок RU*</label>
                                <input type="text" id="title_ru" name="title_ru" class="form-control title_for_slug" required value="{{ old('title_ru', ($docAction->title_ru) ? $docAction->title_ru : '') }}">
                                @if($errors->has('title_ru'))
                                    <em class="invalid-feedback">
                                        {{ $errors->first('title_ru') }}
                                    </em>
                                @endif
                            </div>
                            <div class="form-group {{ $errors->has('title_ua') ? 'has-error' : '' }}">
                                <label for="title_ru">Заголовок UA*</label>
                                <input type="text" id="title_ua" name="title_ua" class="form-control" required value="{{ old('title_ua', ($docAction->title_ua) ? $docAction->title_ua : '') }}">
                                @if($errors->has('title_ua'))
                                    <em class="invalid-feedback">
                                        {{ $errors->first('title_ua') }}
                                    </em>
                                @endif
                            </div>
                            <div class="form-group {{ $errors->has('title_ua') ? 'has-error' : '' }}">
                                <label for="title_ru">Заголовок EN*</label>
                                <input type="text" id="title_en" name="title_en" class="form-control" required value="{{ old('title_en', ($docAction->title_en) ? $docAction->title_en : '') }}">
                                @if($errors->has('title_en'))
                                    <em class="invalid-feedback">
                                        {{ $errors->first('title_en') }}
                                    </em>
                                @endif
                            </div>

                        </div>
                        <div class="col-md-4">

                            <div class="form-group">
                                <div class="toggle-label">Активность</div>
                                <div class="toggle-btn @if($docAction->active == 1) active @endif">
                                    <input type="checkbox" class="cb-value" name="active" value="1" @if($docAction->active == 1) checked @endif />
                                    <span class="round-btn"></span>
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="slug">Сортировка</label>
                                <input type="number" id="sort" name="sort" class="form-control" min="1" max="999999" value="{{ old('sort', ($docAction->sort) ? $docAction->sort : 10) }}">
                            </div>

                            <div class="form-group {{ $errors->has('file') ? 'has-error' : '' }}">
                                <label for="image">Документ</label><br />
                                <label class="label" data-toggle="tooltip" title="Загрузить документ">
                                    <input type="file" class="" name="file">
                                </label>
                                @if($errors->has('file'))
                                    <em class="invalid-feedback">
                                        {{ $errors->first('file') }}
                                    </em>
                                @endif
                                @if($docAction->link != '')
                                    <br />
                                    <input type="checkbox" name="del-pic" value="1"> удалить<br />
                                    <a class="btn btn-secondary btn-sm" href="{{ $docAction->link }}" role="button" target="_blank">Открыть <i class="fas fa-share"></i></a>

                                @endif
                            </div>
                        </div>
                    </div>
                </div>



            </div>
            <div>
                <button class="btn btn-success" type="submit"><i class="fas fa-check"></i> Сохранить</button>
                <a href="/admin/docactions" class="btn btn-secondary"><i class="fas fa-remove"></i> Отменить</a>
            </div>

        </form>
    </div>
</div>

@endsection

@section('scripts')
@endsection

resources/views/admin/docactions/index.blade.php
@extends('layouts.admin')
@section('title')
    Акции
@endsection
@section('styles')
    <style>
        .form-inline label{
            display: inline-block;
        }
        .w-80{
            width:80px!important;
        }
        .w-160{
            width:160px!important;
        }
        .table img{
            max-width:100px;
            max-height: 80px;
        }
        .i-sort{
            cursor:pointer;
        }
        .sort-hide{
            display: none;
        }
        .sort-show{
            display: inline-block;
        }
        .table-responsive{
            padding-bottom: 50px;
        }
    </style>
@endsection
@section('content')
    @can('tag_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route("admin.docactions.create") }}">
                    <i class="fas fa-plus"></i> Создать Акцию
                </a>
            </div>
        </div>
    @endcan


    <div class="card">
        <div class="card-header">
            Акции
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th style="min-width: 60px"></th>
                            <th style="min-width: 150px">Название RU</th>
                            <th style="min-width: 150px">Название UA</th>
                            <th style="min-width: 150px">Название EN</th>
                            <th>Активность</th>
                            <th>Сортировка</th>
                            <th>Ссылка</th>
                            <th style="min-width: 60px">ID</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($docActions as $key => $item)
                            <tr id="item-{{ $item->id }}">
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-bars"></i>
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            @can('tag_edit')
                                                <a class="dropdown-item" href="/admin/docactions/{{$item->id}}/edit"><i class="fas fa-pencil-alt"></i> Редактировать</a>
                                            @endcan
                                            @can('tag_delete')
                                                <a class="dropdown-item btn-item-del" href="" target="_blank" data-id="{{$item->id}}" data-title="{{ $item->title_ru }} [{{ $item->id }}]" data-url="/admin/docactions/{{ $item->id }}"><i class="fas fa-trash"></i> Удалить</a>
                                            @endcan
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <a href="/admin/docactions/{{$item->id}}/edit" title="Редактировать">{{ $item->title_ru ?? '' }}</a>
                                </td>
                                <td>
                                    <a href="/admin/docactions/{{$item->id}}/edit" title="Редактировать">{{ $item->title_ua ?? '' }}</a>
                                </td>
                                <td>
                                    <a href="/admin/docactions/{{$item->id}}/edit" title="Редактировать">{{ $item->title_en ?? '' }}</a>
                                </td>
                                <td>
                                    @if($item->active == true)
                                        <span class="badge badge-success">Да</span>
                                    @else
                                        <span class="badge badge-danger">Нет</span>
                                    @endif
                                </td>
                                <td>
                                    {{ $item->sort }}
                                </td>
                                <td>
                                    @if($item->link != '')
                                        <a class="btn btn-secondary btn-sm" href="{{ $item->link }}" role="button" target="_blank">Открыть <i class="fas fa-share"></i></a>
                                    @endif
                                </td>
                                <td>
                                    <a href="/admin/docactions/{{$item->id}}/edit" title="Редактировать">{{ $item->id }}</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div>
                {{ $docActions->appends(request()->except('page'))->links() }}
            </div>
        </div>
    </div>


    @section('scripts')
        <script>

        </script>
    @endsection
@endsection

resources/views/admin/docactions/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('global.user.title') }}
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th>
                        {{ trans('global.user.fields.name') }}
                    </th>
                    <td>
                        {{ $user->name }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.email') }}
                    </th>
                    <td>
                        {{ $user->email }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.email_verified_at') }}
                    </th>
                    <td>
                        {{ $user->email_verified_at }}
                    </td>
                </tr>
                <tr>
                    <th>
                        Roles
                    </th>
                    <td>
                        @foreach($user->roles as $id => $roles)
                            <span class="label label-info label-many">{{ $roles->title }}</span>
                        @endforeach
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@endsection